<?php

namespace App\Services;

use App\Repositories\AuthorRepository;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class AuthorService extends BaseService
{
    protected $repository;

    public function __construct(AuthorRepository $repository)
    {
        $this->repository = $repository;
    }

    public function save(Request $request): Model
    {
        $nome = $request->input('nome');
        if (strlen(($nome)) > 40) {
            throw new \Exception('Nome não pode ser maior que 40 caracteres');
        }
        return parent::save($request); // TODO: Change the autogenerated stub
    }

    public function delete(int|string $id): void
    {
        $author = $this->repository->find($id, ['books']);
        if (count($author->books) > 0) {
            throw new \Exception('Author possui livros relacionados');
        }
        parent::delete($id);
    }
}
